# Generated by Django 5.1 on 2024-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_ru', models.CharField(max_length=50, unique=True)),
                ('zodiac_en', models.CharField(max_length=50, unique=True)),
                ('start_day', models.CharField(max_length=20, unique=True)),
                ('end_day', models.CharField(max_length=50, unique=True)),
                ('svg', models.TextField(max_length=50, unique=True)),
            ],
        ),
    ]
